### PR TITLE
FLO-131 - Encore Route and Service Order Integrations

### PR DESCRIPTION
**Pull request by pfifieldRW**
Created EncoreRouteCreated and EncoreServiceOrderCreated with a simple schema because we will post much larger JSON in blob storage.
Created EncoreRouteDetailCreated and EncoreServiceOrderDetailCreated; these are the JSON files and schema that will be related to blob storage.

### CODE REVIEW

**Review by lukec — CHANGES_REQUESTED** [review]
Now that we've got a stable place for these files, I'd like you to revisit the 2 main (non-Detail) schemas:
1. Update `title` please
2. Update `URL` attribute to be more self-documenting - Ideally it should link to the (future) URL on routeware.events where future readers can find more about the *Detail event schema.
3. I wonder if it would be helpful for consumers if we either moved or copied a couple of the top-level fields in the *Detail to the corresponding referencing schema. Like `AsOf` and `Tenant` I could imagine being handy to have in the event, without needing to pull down the resource URL.  (open to your thoughts on this one.)

If you can at fix #1 and #2 and think about #3 i'll be 👍

**Comment by pfifieldRW** [comment]
Nice catch with the 1st item!  Good idea with the 2nd item!  I made changes with regards to both.

With regards to the 3rd item... now that you've said that... I like that idea as well.  I would make a case to move the Source field(i.e. com.routeware.encore) over to the main schema as well.  I'll have to make an Encore change, but I think it's a change worth making.

**Comment by lukec** [comment]
I don't think we should have `Source` - this field will be included in the data structure surrounding this event.

**Review by lukec — APPROVED** [review]
LGTM!

**Pull request merged**
